import './globals.css'
import type { Metadata } from 'next'

import NavMenu from '@/components/NavMenu'

export const metadata: Metadata = {
  title: 'Filipe folio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <NavMenu />
        {children}
      </body>
    </html>
  )
}